### ISSUE TITLE
RawGit has reached the end of its useful life

### ISSUE THREAD

**Issue by umbe1987** [walkermatt/ol-layerswitcher#104]
Just to inform you that RawGit has reached the end of its useful life.
[https://rawgit.com/](https://rawgit.com/)

**Comment by walkermatt** [comment]
Yeah saw that, it's a shame as it's been a useful service. I'll take a look at alternatives.

**Comment by walkermatt** [comment]
It looks like https://raw.githack.com/ could be a drop in replacement to https://rawgit.com/.

Provider | Link
------------ | -------------
RawGit | http://rawgit.com/walkermatt/ol-layerswitcher/master/examples/layerswitcher.html
RawGitHack | http://raw.githack.com/walkermatt/ol-layerswitcher/master/examples/layerswitcher.html

@ThomasG77 have you looked at alternatives to RawGit?

**Comment by ThomasG77** [comment]
Using the one you mentioned  (easy to remember and change from original URL simple) plus https://twitter.com/ThomasG77/status/1049417230591635456

**Comment by walkermatt** [comment]
@ThomasG77 thanks, looks like I liked that tweet at the time :man_shrugging:
