### ISSUE TITLE
disable checkbox and grey out layername not working in sidebar.js

### ISSUE THREAD

**Issue by umbe1987** [walkermatt/ol-layerswitcher#107]
Referring to the implementation in #51.

It seems adding `minResolution `and `maxResolution `to `examples/sidebar.js ` does not work (it does not grey out layers in the panel rendered in the sidebar).

**test**
```
new ol.layer.Group({
    title: 'Overlays',
    layers: [
        new ol.layer.Image({
            title: 'Countries',
            minResolution: 500,
            maxResolution: 5000,
            source: new ol.source.ImageArcGISRest({
                ratio: 1,
                params: {
                    'LAYERS': 'show:0'
                },
                url: "https://ons-inspire.esriuk.com/arcgis/rest/services/Administrative_Boundaries/Countries_December_2016_Boundaries/MapServer"
            })
        })
    ]
})
```

I am wondering if this is one of those cases where the user needs to re-render the panel again...

If so, I think it would be better to implement something that would automatically take care of this.

**Comment by umbe1987** [comment]
> I am wondering if this is one of those cases where the user needs to re-render the panel again...

Specifically, I am referring to the comment and code in these lines of code:
https://github.com/walkermatt/ol-layerswitcher/blob/4ac95e35ea1d5b96331332c228b259804fb30944/examples/sidebar.js#L62-L68

**Comment by walkermatt** [comment]
@umbe1987 yes you're right as it stands the user would have to re-render the panel themselves. I've been trying to avoid getting into maintaining listeners on the view/ layers as it gets complicated tracking all the possible events (adding/ removing layers, visibility, changes to the zoom etc.)
