### ISSUE TITLE
visible: 'false', not working

### ISSUE THREAD

**Issue by AllroadsNL** [walkermatt/ol-layerswitcher#108]
[I took this addlayer example](https://github.com/walkermatt/ol-layerswitcher/blob/master/examples/addlayer.html)
with the mentioned js and css.
fitted a line
`			visible: 'false',`

and the code is
`    overlayGroup.getLayers().push(
        new ol.layer.Image({
            title: 'Countries',
			visible: 'false',
            minResolution: 500,
            maxResolution: 5000,
            source: new ol.source.ImageArcGISRest({
                ratio: 1,
                params: {'LAYERS': 'show:0'},
                url: "https://ons-inspire.esriuk.com/arcgis/rest/services/Administrative_Boundaries/Countries_December_2016_Boundaries/MapServer"
            })
        })
    );`
 I expected the Countries image overlay as unchecked.
But I got this, checked
![unchecknot](https://user-images.githubusercontent.com/8817345/47450460-94d02c00-d7c5-11e8-86cc-7375a1cae45f.png)
As mentioned in: 
[ol/layer/Image API](https://openlayers.org/en/latest/apidoc/module-ol_layer_Image.html)
visible | boolean | <optional> | true | Visibility.

**Comment by walkermatt** [comment]
Hi, try:

`visible: false`

In JavaScript `'false'` is a non-empty string which will evaluate to `true`.

**Comment by AllroadsNL** [comment]
Thanks !! Your right.
