### ISSUE TITLE
sidebar example is broken

### ISSUE THREAD

**Issue by umbe1987** [walkermatt/ol-layerswitcher#111]
I think it's the only one not working due to a dated openlayers js and css reference (v4.6.4 against v5.1.3) in the html example. Will try to fix it with a PR when I can if you want.

**Comment by walkermatt** [comment]
Thanks, what issue are you seeing? I tested in FF, Chrome and Edge prior to merging.

**Comment by umbe1987** [comment]
I've made a simple PR to fix this. Cheers!
