### ISSUE TITLE
warning multiple modules with names that only differ in casing

### ISSUE THREAD

**Issue by stackedone** [walkermatt/ol-layerswitcher#166]
I have some warnings in my angular 7 application. These are the same as #79 and the fix is merged into the versions. How can i fix this?  
"ol": "^5.3.0", "ol-layerswitcher": "^3.2.0",

`WARNING in ./node_modules/ol/Layer/Base.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

/Users/wim/development/ng7-demo/node_modules/ol/Layer/Base.js
Used by 2 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/Layer/Layer.js
/Users/wim/development/ng7-demo/node_modules/ol/layer/Base.js
Used by 4 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/layer/Group.js
WARNING in ./node_modules/ol/Layer/Layer.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

/Users/wim/development/ng7-demo/node_modules/ol/Layer/Layer.js
Used by 2 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/Layer/Tile.js
/Users/wim/development/ng7-demo/node_modules/ol/layer/Layer.js
Used by 9 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/layer/Vector.js
WARNING in ./node_modules/ol/Layer/Property.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

/Users/wim/development/ng7-demo/node_modules/ol/Layer/Property.js
Used by 22 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/Layer/Layer.js
/Users/wim/development/ng7-demo/node_modules/ol/layer/Property.js
Used by 22 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/layer/Base.js
WARNING in ./node_modules/ol/Source/Source.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

/Users/wim/development/ng7-demo/node_modules/ol/Source/Source.js
Used by 2 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/Source/Tile.js
/Users/wim/development/ng7-demo/node_modules/ol/source/Source.js
Used by 2 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/source/Vector.js
WARNING in ./node_modules/ol/Source/State.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

/Users/wim/development/ng7-demo/node_modules/ol/Source/State.js
Used by 2 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/Source/Source.js
/Users/wim/development/ng7-demo/node_modules/ol/source/State.js
Used by 14 module(s), i. e.
/Users/wim/development/ng7-demo/node_modules/ol/layer/Group.js
`

**Comment by walkermatt** [comment]
Closing in this repo as I think this issue relates to [OpenLayers](https://github.com/openlayers/openlayers/) itself and not ol-layerswitcher.
