### ISSUE TITLE
Is it possible to toggle visibility of more layers at a time

### ISSUE THREAD

**Issue by peterspliid** [walkermatt/ol-layerswitcher#174]
I wish to group several layers, so they appear as one layer in the layerswitcher, so when I change the checkbox, it shows/hides several layers at once.

It could be fixed if the layerswitcher fires an event when hiding a layer, so I can hide another layer when that layer is toggled. I can't however find an event for that. Or is there any other way to do this?

**Comment by kennethhaspeel** [comment]
I've been trying the same thing but no luck so far. I've tried making a group layer (to group the layers) and then adding that group to another group which has a title and a type base. The map shows so the group works but it's not added in the layerswitcher

**Comment by walkermatt** [comment]
@peterspliid we've been working on allowing visibility to be controlled via groups in this PR, see from this comment: https://github.com/walkermatt/ol-layerswitcher/pull/132#issuecomment-496654601

**Comment by walkermatt** [comment]
I've just published [v3.3.0](https://www.npmjs.com/package/ol-layerswitcher/v/3.3.0) which I think covers this use case, see the [`groupSelectStyle` option in the docs](../#layerswitcher) and Selectable groups example (under [examples](../#examples)).
