### ISSUE TITLE
Missing LayerSwitcher in OpenLayers 5?

### ISSUE THREAD

**Issue by Wejden22** [walkermatt/ol-layerswitcher#179]
I was wondering if there is a LayerSwitcher control in OpenLayers 5?

I read that ol5 is a complete rewrite. But I can't seem to find the equivalent of LayerSwitcher from https://openlayers.org/en/latest/apidoc/module-ol_control.html. I don't see how one can turn on and off layers without this control. Is LayerSwitcher renamed to something else, missing or is the documentation incomplete?

If OpenLayers 5 does not have LayerSwitcher, does anyone know of an example that implements a custom control like the old LayerSwitcher?

**Comment by walkermatt** [comment]
@Wejden22 [this repo](https://github.com/walkermatt/ol-layerswitcher) implements a layer switcher for OpenLayers 5. If you look through the issues you will see that some people have adapted it to look more like the OpenLayers 2 layer switcher if that's what you're after.

**Comment by Wejden22** [comment]
Same , its  not working !

**Comment by walkermatt** [comment]
Have you also included the CSS along with the JS?

**Comment by Wejden22** [comment]
yes !

**Comment by Wejden22** [comment]
Working !!  Thank you
