### ISSUE TITLE
Problem with OSM Map OpenLayers 5 : the map won't show

### ISSUE THREAD

**Issue by Wejden22** [walkermatt/ol-layerswitcher#181]
var map3 = new ol.Map({
      layers:  new ol.layer.Tile({
        source: new ol.source.OSM()
      }) ,
    target: 'map-id3',
    view: new ol.View({
      center:ol.proj.fromLonLat([10.74,34.77]),
      zoom:12
    }) 

  });

**Comment by walkermatt** [comment]
Please raise general OpenLayers support questions on [stackoverflow with the tag `openlayers`](https://stackoverflow.com/questions/tagged/openlayers).
