### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by LandonMarshall** [walkermatt/ol-layerswitcher#194]
I love this layerswitcher, and am using it via npm install, but it has a few bugs since I am using the latest release(which is quite old). I pulled the latest code, and it works perfectly for me but I would like to use the official releases. Thanks in advance!

**Comment by walkermatt** [comment]
Yes, it's been a while :smile_cat:. I'm planning on a release once https://github.com/walkermatt/ol-layerswitcher/pull/132 is merged which should be soon.

**Comment by walkermatt** [comment]
I've just published [v3.3.0](https://www.npmjs.com/package/ol-layerswitcher/v/3.3.0).

**Comment by LandonMarshall** [comment]
Thank you! It works perfectly now.
