### ISSUE TITLE
Support for custom vector layers

### ISSUE THREAD

**Issue by josromgav** [walkermatt/ol-layerswitcher#203]
Hi, I have used this layerswitcher in a few projects already and i find it quite useful.
It wasn't untill now that i wanted to select and unselect (checkbox) custom vector source layers (source: new ol.source.Vector()) but it gives me an error every time I try to show them through the panel interface or showing them by default.

Every example I find online is using third party sources for tile layers, so it brings me the question about the actual support for custom features layers. 

The error is the following and it points me to the idea that it wont currently work with vector source:
Uncaught TypeError: u.getTileGridForProjection is not a function
at e.prepareFrame (TileLayer.js:148)
    at e.renderFrame (Map.js:159)
    at e.renderFrame_ (PluggableMap.js:1232)
    at e.<anonymous> (PluggableMap.js:191)

Declaring a layer like this, will trigger the error:
new ol.layer.Tile({
    source: new ol.source.Vector(),
    title: 'Points of Interest',
    visible: false,
    zIndex: 20
}),

**Comment by walkermatt** [comment]
Hi, have you tested your vector layer independently of the layerswitcher? The error doesn't appear to be directly related to the layerswitcher but more a problem with your layer definition. There are quite a few [examples of using vector layers](https://openlayers.org/en/latest/examples/?q=vector).
