### ISSUE TITLE
The layer switcher obscures the "return to north" arrow

### ISSUE THREAD

**Issue by myfta** [walkermatt/ol-layerswitcher#205]
Standard functionality in Openlayers is such that when a map is rotated a "return to north" arrow appears in the top right of the screen. The layer switcher icon seems to obscure this icon and therefore the functionality is lost.

See [https://github.com/tomchadwin/qgis2web/issues/774#issue-469460183], where the problem was discovered.

**Comment by walkermatt** [comment]
I think the current [ol-layerswitcher CSS](https://github.com/walkermatt/ol-layerswitcher/blob/master/src/ol-layerswitcher.css#L11) ensures the rotate button is not obscured. Try rotating the map in the [default example](https://raw.githack.com/walkermatt/ol-layerswitcher/master/examples/layerswitcher.html).

/cc @tomchadwin

**Comment by myfta** [comment]
Correct. Thank you. I had tweaked the CSS to achieve this effect in the interim.
