### ISSUE TITLE
Can we add an event dispatch to LayerSwitcher.renderPanel()?

### ISSUE THREAD

**Issue by umbe1987** [walkermatt/ol-layerswitcher#209]
I see that after #132 the static method [`renderPanel()`](https://github.com/walkermatt/ol-layerswitcher/blob/a9d983c0e8e6286cf32779cc690ff1773f0d9bb5/src/ol-layerswitcher.js#L129) has a new internal call to itself:

        var ul = document.createElement('ul');
        panel.appendChild(ul);
        // passing two map arguments instead of lyr as we're passing the map as the root of the layers tree
        LayerSwitcher.renderLayers_(map, map, ul, options, function render(changedLyr) {
            // console.log('render');
            LayerSwitcher.renderPanel(map, panel, options);
        });

As this (I suppose) is re-rendering the layer tree state according to the new [`groupSelectStyle`](https://github.com/walkermatt/ol-layerswitcher/#layerswitcher) option, would it be reasonable to trigger a "render" event (or similar) so that users (like me) knows when the rendering does occur besides the call to `LayerSwitcher.renderPanel()`?

Please, correct me if my supposision is wrong, but for me this is crucial as I need to take actions when the panel draws, and if it draws indipendently of the user, it would be nice to be warned by aJS event in my opinion.

I would be more than happy to make a PR for this!

**Comment by walkermatt** [comment]
@umbe1987 I'd be happy with adding a render event. It should probably be dispatched once the panel had been rendered?

**Comment by umbe1987** [comment]
Maybe a "render" could be fired up when the method is called and "rendercomplete" when it finishes much like is done in [OpenLayers](https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/render/EventType.js)?

**Comment by walkermatt** [comment]
Sounds like a plan 👍

**Comment by walkermatt** [comment]
Now merged
