### ISSUE TITLE
Return name of current top displayed layer

### ISSUE THREAD

**Issue by JackLidge** [walkermatt/ol-layerswitcher#221]
Hey everyone,

I'm trying to use layerswitcher in the sidebar to create a dropdown list of times from the current top displayed WMS layer, and I was wondering if it was possible using LayerSwitcher to get it to return the current top displayed layer?

If I can get the top displayed layer, then I can do a WMS Capabilities query on the layer to discover what all the time values of the layer are.

**Comment by walkermatt** [comment]
Hi, you can determine the top most visible layer by looping through the layers that the map contains. If you have nested layers you could use the `LayerSwitcher.forEachRecursive` function to loop through layers and groups. Docs: https://github.com/walkermatt/ol-layerswitcher#foreachrecursive

**Comment by JackLidge** [comment]
Thanks for linking to that @walkermatt, I managed to get it to work using the .forEachRecursive method.
