### ISSUE TITLE
Parent/child group selection doesn't seem to work in sidebar-v2 example

### ISSUE THREAD

**Issue by DrMeers** [walkermatt/ol-layerswitcher#225]
Configuring as per http://raw.githack.com/walkermatt/ol-layerswitcher/master/examples/sidebar.html seems to lose some of the functionality for child/parent checkbox interactions -- e.g. the "minus" symbols for partial group selection don't appear, and deselecting a parent doesn't clear the child checkboxes, etc. How can we keep this nice functionality, but still mounting the LayerSwitcher within the sidebar?

**Comment by umbe1987** [comment]
Might be related to #209?

**Comment by umbe1987** [comment]
Or... I guess it has to do with these lines https://github.com/walkermatt/ol-layerswitcher/blob/a9d983c0e8e6286cf32779cc690ff1773f0d9bb5/src/ol-layerswitcher.js#L129-L131

...

https://github.com/walkermatt/ol-layerswitcher/blob/a9d983c0e8e6286cf32779cc690ff1773f0d9bb5/src/ol-layerswitcher.js#L145-L152

It seems calling the static `renderPanel` without explicitly defining any `options` param will not trigger neither `LayerSwitcher.setGroupVisibility` nor `LayerSwitcher.setChildVisibility`.

This is just an assumption though...

**Comment by walkermatt** [comment]
@umbe1987 thanks for looking into this, your right it's due to `LayerSwitcher.renderPanel` not setting a default `groupSelectStyle` if one is not provided. I think I've a fix which I'm testing ATM

**Comment by walkermatt** [comment]
@DrMeers, @umbe1987 I think this is fixed, can you test (the [sidebar example](https://raw.githack.com/walkermatt/ol-layerswitcher/master/examples/sidebar.html) should be updated shortly) then I'll do a dot release once we are happy.

**Comment by umbe1987** [comment]
@walkermatt that is looking soooooo good! Thanks a lot!

**Comment by walkermatt** [comment]
Published as [v3.4.0](https://www.npmjs.com/package/ol-layerswitcher/v/3.4.0)

**Comment by DrMeers** [comment]
Thanks @walkermatt and @umbe1987 :)
