### ISSUE TITLE
Fold button submits forms

### ISSUE THREAD

**Issue by mstenta** [walkermatt/ol-layerswitcher#259]
If you use the `fold` property to collapse a layer group, and the map is within a form, clicking the arrow (which is a `<button>`) to expand the group submits the form.

I think we just need to add `e.preventDefault();` to fix this. Here is the click function:

https://github.com/walkermatt/ol-layerswitcher/blob/32735005cb5eaa3c20310856dc346fb0261f7c4c/src/ol-layerswitcher.js#L308

For reference, here is the click callback for the main LayerSwitcher button, which does have a `e.preventDefault();` in it:

https://github.com/walkermatt/ol-layerswitcher/blob/32735005cb5eaa3c20310856dc346fb0261f7c4c/src/ol-layerswitcher.js#L57

**Comment by mstenta** [comment]
I created a pull request for review: #260

**Comment by walkermatt** [comment]
@mstenta thanks for reporting and the PR 👍

**Comment by mstenta** [comment]
Thanks @walkermatt for reviewing and merging!

Do you foresee a new tagged release in the near future? No rush - just curious. I'm referencing a specific commit in my package.json now.

**Comment by walkermatt** [comment]
Just published https://www.npmjs.com/package/ol-layerswitcher/v/3.5.0 :tada:

**Comment by mstenta** [comment]
Terrific! Thank you!
