### ISSUE TITLE
Typescript and typing fails

### ISSUE THREAD

**Issue by oehm-smith** [walkermatt/ol-layerswitcher#272]
Following on from #75 comes the problem of typing when using Typescript:

    import LayerSwitcher from 'ol-layerswitcher';

    ...
    this.map.addControl(new LayerSwitcher());

However there is a problem because the options to the Layers does not include the fields that `ol-layerswitcher` is looking for:

### OpenLayers

	export interface Options {
		opacity?: number;
		visible?: boolean;
		extent?: Extent;
		zIndex?: number;
		minResolution?: number;
		maxResolution?: number;
		preload?: number;
		source?: TileSource;
		map?: PluggableMap;
		useInterimTilesOnError?: boolean;
	}
	export default class TileLayer extends Layer {
		constructor(opt_options?: Options);
                ...

### My code

    const mainMap = new TileLayer({
      source: new OSM(),
      title: 'Open Street Map',
      type: 'base'
    });
    mainMap.set('name', 'Main map');

    this.map = new Map({
      target: 'map',
      layers: [
        mainMap,
      ],
      ....

### Transpile it

	ERROR in src/app/eow-map.ts:33:7 - error TS2345: Argument of type '{ source: OSM; title: string; type: string; }' is not assignable to parameter of type 'Options'.
	  Object literal may only specify known properties, and 'title' does not exist in type 'Options'.

	33       title: 'Open Street Map',

@walkermatt given your closer ties to the openlayers team what do you think can be done?

**Comment by oehm-smith** [comment]
I have a solution:

    const mainMap = new TileLayer({
      source: new OSM()
    });
    mainMap.set('name', 'Main map');
    mainMap.set('title', 'Open Street Map');
    mainMap.set('type', 'base');

Now I just need to get button and menu showing properly ...

**Comment by walkermatt** [comment]
@oehm-smith have you included the main CSS file in your project? See the [CSS section in the README](https://github.com/walkermatt/ol-layerswitcher#css-1).

**Comment by oehm-smith** [comment]
Its all good now, thanks @walkermatt.

**Comment by umbe1987** [comment]
> I have a solution:
> 
> ```
> const mainMap = new TileLayer({
>   source: new OSM()
> });
> mainMap.set('name', 'Main map');
> mainMap.set('title', 'Open Street Map');
> mainMap.set('type', 'base');
> ```
> 
> Now I just need to get button and menu showing properly ... I had to do similar changes to #18 though I don't need scroll bars.

Thanks, this has been useful to me!
