### ISSUE TITLE
LayerSwitcher click events are propagated to ol map

### ISSUE THREAD

**Issue by skitourenguru** [walkermatt/ol-layerswitcher#279]
If the user changes the active layers with the LayerSwitcher and the click occurs by chance over a map feature, not only the LayerSwitcher handles the event, but the event is also propagated to the ol map and the feature is clicked.
How to stop event propagation from the LayerSwitcher to the ol map?

**Comment by walkermatt** [comment]
Hi, this should be fixed in a future ol release (see https://github.com/openlayers/openlayers/pull/10502)

**Comment by skitourenguru** [comment]
Since I recently updated ol, it is fixed.
