### ISSUE TITLE
text direction

### ISSUE THREAD

**Issue by Alish84** [walkermatt/ol-layerswitcher#286]
how can I change text direction from right to left for the layer group name and all the others...

**Comment by walkermatt** [comment]
Hi, Can you share a mockup or screenshot showing how you would expect the tree to look like when rendered right-to-left? Do you know how other similar projects handle this?

**Comment by Alish84** [comment]
Hi
Thank you for responding. I wanted to change the group layer name and the tree to align-right. I changed .layer-switcher { text-align: right; } but it didn't work. I had something like this.  
![](https://user-images.githubusercontent.com/46603950/78123725-dab20a80-7423-11ea-8e86-f72927259c1c.png)
I was quite disappointed that I deleted haphazardly my browser history and it just worked
![Untitled](https://user-images.githubusercontent.com/46603950/79017710-3ba9b300-7b87-11ea-8af2-21181c733d93.png)

**Comment by walkermatt** [comment]
Ah OK, so is that what you'd expect? Is there anything else that would need to change in order to support right to left text direction?

**Comment by Alish84** [comment]
I'm working on a personal webGIS that cover all geospatial data of my country and I have a plan to develop it to the whole world. My first reason for creating this is to help student especially those dealing with geoscience(including Geology, GIS&RS and ...) that can do their dissertation in the best way. I am going to add any data, learning course, free software, and all the things relating to geospatial science, study, system, field , and so on for free. I believe that this can help our Earth is a good place to live, to deal with environmental problems, to deal with climate change, to optimally allocate resources to locations ...

**Comment by Alish84** [comment]
Oh no, I'm good. Thanks for your attention. All the thing I need is changing #text-align in #css and The problem was solved.

**Comment by Alish84** [comment]
And finally, thank you #walkermatt for this good #ol-layerswitcher

**Comment by walkermatt** [comment]
No worries, you're very welcome. Glad you're sorted 👍
