### ISSUE TITLE
Package Out of Date

### ISSUE THREAD

**Issue by bobermen1** [walkermatt/ol-layerswitcher#290]
I am using this to get the package:
<script src="https://unpkg.com/ol-layerswitcher@3.5.0"></script>

The js it pulls down seems to be missing the click activation mode code.

**Comment by walkermatt** [comment]
Thanks for the nudge. I've just published [v3.6.0 to npm](https://www.npmjs.com/package/ol-layerswitcher/v/3.6.0).
