### ISSUE TITLE
Icon is getting cropped

### ISSUE THREAD

**Issue by MtnBiker** [walkermatt/ol-layerswitcher#301]
ol/ol.css sets height and width to 1.375em over-riding 38px set by layerswitcher.
[http://knobby.ws/toShare/Icon_cropped_with_css.png](Image showing cropping and css) from Chrome, but same in Safari.

box-sizing is the same, with margins are changed from what they are when ol.css is not involved.

I tried not having ol/ol.css but then the map cannot be moved with the mouse. I imagine there are other problems too.

ol v6.2.1. This part of a Rails 6 app.

All the ol:

    import 'ol/ol.css';
    import Map from 'ol/Map';
    import View from 'ol/View';
    import GeoJSON from 'ol/format/GeoJSON';
    import VectorLayer from 'ol/layer/Vector';
    import VectorSource from 'ol/source/Vector';
    import {Fill, Stroke, Style, Text} from 'ol/style';
    import Icon from 'ol/style/Icon';
    import { transform } from 'ol/proj';
    import LayerGroup from 'ol/layer/Group';
    import LayerTile from 'ol/layer/Tile';
    import OSM from 'ol/source/OSM';
    import XYZ from 'ol/source/XYZ';
    import LayerSwitcher from 'ol-layerswitcher';
    import { transformExtent, fromLonLat } from 'ol/proj';

I'm a newbie to OpenLayers and not much better with JavaScript and CSS.

Thanks for any help. I'm going to try putting in my own css, but suspect this is a subtle bug.

**Comment by walkermatt** [comment]
I think the issue is due to the fact that `ol.css` is being loaded after `ol-layerswitcher.css`. If you've installed the [ol-layerswitcher package](https://www.npmjs.com/package/ol-layerswitcher) via npm then you can import `ol-layerswitcher.css` after `ol.css` in your main JavaScript file:

```js
import 'ol/ol.css';
import 'ol-layerswitcher/src/ol-layerswitcher.css';
...
```

**Comment by MtnBiker** [comment]
Thank you. I thought it was something like that. But I'm not familiar enough with the asset pipeline to have quite figured it out. Needed to put `@import 'ol/ol.css';` in application.scss and remove from the specific .js file.
