### ISSUE TITLE
Title lengths?

### ISSUE THREAD

**Issue by movethathoof** [walkermatt/ol-layerswitcher#335]
Hello, my apologies if this is mentioned somewhere  - I looked through the examples and documentation and didn't find anything - but I can't find a way to have longer titles for uncombined layers stay on the same line as their selection box. I've attached two photos that demonstrate what I mean: if a layer is not combined and it has a long title then it automatically will skip to a new line from its selection box. If the title is shorter, it remains on that line (or, as can be seen with the other layers below, if it is combined it also starts on that line). I tried inserting a break after a portion of the text, which did not have the desire effect. Have I missed something?

Thank you!

![Legend Title 1](https://user-images.githubusercontent.com/66330402/86956337-87d0a900-c11e-11ea-9609-db076beb82bd.png)
![Legend Title 2](https://user-images.githubusercontent.com/66330402/86956339-87d0a900-c11e-11ea-9c29-722665a0383c.png)

**Comment by walkermatt** [comment]
Hi, do you have a link to an example that illustrates the issue?

**Comment by movethathoof** [comment]
Hi! Sorry that this reply is so delayed - I tried throwing together[ a plunkr, but could only get the layer switcher to work with layers collapsed](https://plnkr.co/edit/R4XzS5XxbspPQ92E?preview), making it useless as demonstration of this issue.

That meant I had to wait until I could get it up elsewhere, which altered the issue somewhat,. [Here](https://www.sundrytangents.net/map2/) you can see the issue as I first raised it, where the title is moved to a different line from the arrow and checkbox. 

However, in putting together this demonstration I found that there seems to be a conflict with the Bootstrap css that is also loaded on some pages, for, [as demonstrated here](https://www.sundrytangents.net/map1/), when there is no Bootstrap css the title remains on the right line. That said, regarding style and consistency, you can see that that title begins on the next line from the arrow, unlike every other that begins aligned with where the title begins on the first line.

Thank you!

**Comment by walkermatt** [comment]
Hi, I released a new version today which includes some improvement to wrapping of long layer titles. See the [CHANGELOG](https://github.com/walkermatt/ol-layerswitcher/blob/master/CHANGELOG.md#v370) and linked issue for details. I've also updated the [main example](http://raw.githack.com/walkermatt/ol-layerswitcher/master/examples/layerswitcher.html) to include a longer wrapped title. Let me know how you get on.

/cc @devsupportman

**Comment by movethathoof** [comment]
Thank you for the swift reply! The issues here noted about skipping to a new line or where is starts on a new line would appear to have been resolved.

That said, as can be seen on [either](http://localhost:5000/map1/) of [the two](http://localhost:5000/map2/) demonstration maps I shared, when the layers extend past the bottom of the map the scrollbar no longer appears and leaves them inaccessible.

As well, there's still a kind of strange interaction with the Bootstrap CSS - the spacing between lines of the second link ('map2', which loads the bootstrap CSS) is much greater than the first (and the line appears to be slightly lower and not aligned with the checkbox?).

**Comment by walkermatt** [comment]
@devsupportman have you seen this issue with ol-ishare?

> when the layers extend past the bottom of the map the scrollbar no longer appears and leaves them inaccessible.

**Comment by devsupportman** [comment]
> @devsupportman have you seen this issue with ol-ishare?
> 
> > when the layers extend past the bottom of the map the scrollbar no longer appears and leaves them inaccessible.

I think this can be resolved by allowing overflow scrolling and limiting the height on the layer switcher, e.g.: 
```css
.layer-switcher.shown {
    overflow-y: auto;
    max-height: 50%;
}
```

**Comment by walkermatt** [comment]
@movethathoof I've just done some testing and I found that adding the following rule did the trick for me:

```css
.layer-switcher.shown {
  height: calc(100% - 6.5em);
}
```

Tested on Chrome, Firefox, Edge 18 & 86.
