### ISSUE TITLE
Add some kind of "loading" icon?

### ISSUE THREAD

**Issue by kesslerf** [walkermatt/ol-layerswitcher#351]
Hey Guys,
I am using Layerswitcher - Sidebar and there is a Group Layer which is retrieving big amounts of Data from a Geoserver. So far so good, everything is working. 
When a user checks a checkbox of one of the layers in the group layer, or in general when something is loaded to the map, I wanted to add a loading-icon in the middle of the current map-extent. 

If you could give me a hint I would be really thankful. I already googled/checked stackoverflow but was not able to find something that worked.

**Comment by walkermatt** [comment]
Hi, it sounds like the [OpenLayers tile load events example](https://openlayers.org/en/latest/examples/tile-load-events.html) might help.

**Comment by kesslerf** [comment]
Thanks for the hint, guess that will work!

**Comment by kesslerf** [comment]
I am sorry to reopen the issue, but I was not able to get this working, maybe you can help me. In the linked example the source-layer is defined as a variable (var source = new XYZ) and called later on. But since I am using the sidebar I have no variable I can call. I tried using the forEachRecursive-option with the title of my group-layer and a function to show/hide my loading-icon on clicking. 

I would be really happy if you could help me.
