### ISSUE TITLE
How can I remove some layers or layer groups? 

### ISSUE THREAD

**Issue by nobohan** [walkermatt/ol-layerswitcher#357]
Is there a way to remove some layers or layer groups from the layerSwitcher?

We can unset the 'title' key on the layer, but layer title can be useful for other use in the application. 

In OL2, there was a useful option to put on the layer : ` 'displayInLayerSwitcher':false`

**Comment by walkermatt** [comment]
Hi, currently the only way to avoid a layer being displayed is to not set a `title` property.

**Comment by Luooooooo** [comment]
it's better to set a prop as displayInLayerSwitcher
