### ISSUE TITLE
switcher not updated if group visibility changed from code

### ISSUE THREAD

**Issue by mysiar** [walkermatt/ol-layerswitcher#377]
I have a case that I build the base map with LayerSwitcher.
Later on I create groups and set their visibility depend on the config but LayerSwitcher do not see the visibility in Panel.
Is there any way I can hook it to update Switcher based on group visibility ?

**Comment by mysiar** [comment]
> I have a case that I build the base map with LayerSwitcher.
> Later on I create groups and set their visibility depend on the config but LayerSwitcher do not see the visibility in Panel.
> Is there any way I can hook it to update Switcher based on group visibility ?

I found out if I add layer to group and set layer visibility to group visibility that LayerSwitcher is updated the way I wanted :)

**Comment by walkermatt** [comment]
Hi, you can also call the `renderPanel` method of your instance which should update the layers shown in the panel to match the current state of the map 👍
