### ISSUE TITLE
Error in Angular 10

### ISSUE THREAD

**Issue by daudihusbands** [walkermatt/ol-layerswitcher#380]
Hi,
I've just upgraded from angular 9 to 10. My app compiles and runs ok but I'm seeing the following errors

```
    ERROR in node_modules/ol-layerswitcher/dist/ol-layerswitcher.d.ts:255:16 - error TS2665: Invalid module name in augmentation. Module 'ol/layer/Base' resolves to an untyped module at 'C:/Users/.../node_modules/ol/layer/Base.js', which cannot be augmented.

    255 declare module 'ol/layer/Base' {
                     
    node_modules/ol-layerswitcher/dist/ol-layerswitcher.d.ts:278:16 - error TS2665: Invalid module name in augmentation. Module 'ol/layer/Group' resolves to an untyped module at 'C:/Users/.../node_modules/ol/layer/Group.js', which cannot be augmented.
    
    278 declare module 'ol/layer/Group' {
```

**Comment by walkermatt** [comment]
Hi, have you installed the `@types/ol` package?

I think I'm going to simplify how the layer options are defined shortly.

**Comment by walkermatt** [comment]
I've just released [v3.8.1](https://www.npmjs.com/package/ol-layerswitcher/v/3.8.1), see [the CHANGELOG for details](https://github.com/walkermatt/ol-layerswitcher/blob/master/CHANGELOG.md).

**Comment by daudihusbands** [comment]
Thanks @walkermatt. I've upgraded to latest ol, @types/ol and ol-layerswitcher. Works ok.

Had to fix quite a few errors caused by adding the @types/ol package. 
For example 
```js
const layer = new Layer({
title: 'Some title'
})
```
had to be changed to
```js
const layer = new Layer()
layer.set('title', 'Some title')
```

**Comment by walkermatt** [comment]
Great, thanks for the update 👍

You can specify layer options including layer switcher specific properties such as `title` via object literals by importing the extended base and group layer options interfaces as described here: https://github.com/walkermatt/ol-layerswitcher/blob/master/README.md#typescript-type-definition

**Comment by daudihusbands** [comment]
Interesting. Will give it a go.
Thanks again
