### ISSUE TITLE
parcel.js sample, missing all check box, see red circle above screen shot

### ISSUE THREAD

**Issue by hoogw** [walkermatt/ol-layerswitcher#388]
<img width="1950" alt="Screen Shot 2020-12-27 at 10 15 02 AM" src="https://user-images.githubusercontent.com/419582/103177139-975ac000-482c-11eb-82b6-badd33dc88ab.png">
<img width="1943" alt="Screen Shot 2020-12-27 at 9 51 55 AM" src="https://user-images.githubusercontent.com/419582/103176736-354c8b80-4829-11eb-9f93-2cc4132b072f.png">

I have tried parcel.js sample, missing all check box, see red circle above screen shot,

I realize your original sample parcel.js source code,  missing 

                         import 'ol-layerswitcher/dist/ol-layerswitcher.css';

By add above css, still missing all check box, why?

Is it polluted by  with other css? I also have materializedcss, and many other css.

**Comment by hoogw** [comment]
<img width="1754" alt="Screen Shot 2020-12-27 at 10 30 40 AM" src="https://user-images.githubusercontent.com/419582/103177374-c114e680-482e-11eb-86ce-21617e60a893.png">

Radio check box element is there (red line), it does have style, but somehow it was hidden, not showing as expected

by check console, radio style, I realized that radio check box css style was overide by materializecss

So I uncheck, cross line 3 style from materializedcss, (red square, below screen shot), now it shows as expected.

<img width="1763" alt="Screen Shot 2020-12-27 at 10 36 19 AM" src="https://user-images.githubusercontent.com/419582/103177462-95463080-482f-11eb-8643-a2de4029aa89.png">

**Comment by hoogw** [comment]
I have same error fixed by add style tag in html to overwrite opacity to 1

materialize css set radio opacity to 0, we must undo it to 1

[how to fix this issue, click here][1]

[or issue 2 ,  click here][2]


your html add following style tag to overwrite it

             




                            

                                      
                                      
                                        
                                      <style>
                                            [type="radio"]:not(:checked), [type="radio"]:checked {
                                                position: relative; 
                                                opacity: 1; 
                                            }
                                                
                                      </style>

                            
                          

After fix, it works as expected
<img width="2455" alt="Screen Shot 2020-12-27 at 11 17 19 AM" src="https://user-images.githubusercontent.com/419582/103178152-28359980-4835-11eb-8021-13b321a20d86.png">








  [1]: https://github.com/walkermatt/ol-layerswitcher/issues/388
  [2]: https://github.com/walkermatt/ol-layerswitcher-examples/issues/2

**Comment by walkermatt** [comment]
@hoogw sorry for not seeing this issue when it was first created. Thanks for posting your findings.
