### ISSUE TITLE
Is openlayers 6.5 MapBoxVector layer supported?

### ISSUE THREAD

**Issue by asindl** [walkermatt/ol-layerswitcher#397]
Hi there,
I tried to add a MapBoxVector layer to my map according to the [specs](https://openlayers.org/en/latest/apidoc/module-ol_layer_MapboxVector-MapboxVectorLayer.html).
I added title and base and added it to my baselayergroup.
Unfortunately it is not showing up in the layerswitcher dialog. Only the other two layers show up there...

```
var mbLayer = new ol.layer.MapboxVector({
    title: 'MapBox',
    type: 'base',
    styleUrl: 'mapbox://styles/mapbox/bright-v9',
    accessToken: 'your-mapbox-access-token-here'
});

var baseLayerGroup = new ol.layer.Group({
    title: 'Map',
    zIndex: 1,
    layers: [
        esriLayer,
        mbLayer,
        osmLayer
    ]
});
```

**Comment by mike-000** [comment]
Unlike other layer types MapBoxVector does not support additional properties in the constructor, but you could use

```
var mbLayer = new ol.layer.MapboxVector({
    styleUrl: 'mapbox://styles/mapbox/bright-v9',
    accessToken: 'your-mapbox-access-token-here'
});

mbLayer.setProperties({
    title: 'MapBox',
    type: 'base',
});
```

**Comment by asindl** [comment]
Thanks, @mike-000, that worked.
Now, if I add several mapbox layers (light, dark, streets), I can switch the layers, but the theme is always the same. Maybe some Mapbox specific mechanics in the background...
