### ISSUE TITLE
Getting layer selection events 

### ISSUE THREAD

**Issue by minorsecond** [walkermatt/ol-layerswitcher#411]
I'm trying to have a legend which changes depending on the current layer visible, but can't figure out how to get layer selection events so that I can then check which layer is selected in order to change the legend.

Is there any way to do this? I've tried adding an EventListener, but can't get that to work. I'm wondering if there are any built-in ways to do what I'm trying to do.

**Comment by walkermatt** [comment]
Hi, you can probably achieve what you are after by listening to visibility events on the layers themselves. See https://github.com/walkermatt/ol-layerswitcher/issues/30#issuecomment-190136675
