### ISSUE TITLE
The value of deltaPerZoom_ in MouseWheelZoom.js

### ISSUE THREAD

**Issue by lyz1988** [walkermatt/ol-layerswitcher#433]
I saw the code in mouseWheelZoom.js as follows,
_this.deltaPerZoom_ = 300;

Now i faced the question is that, when i scroll the wheel of the mouse to zoom out or in the map,
the value of the map zoom changed is about 0.333333333,
but the vaue of the zoom controls  changed is 1,

how could i keep the value equal, thanks for your help.

**Comment by walkermatt** [comment]
For general questions and support regarding OpenLayers you are best to [create a question on StackOverflow](https://stackoverflow.com/questions/tagged/openlayers).
