### ISSUE TITLE
ol3-layerswitcher integration in ol3-sidebar

### ISSUE THREAD

**Issue by thomasschmiedl** [walkermatt/ol-layerswitcher#46]
Hello,

could someone integrate the layerswitcher in [this ol3-sidebar](https://github.com/Turbo87/sidebar-v2/blob/master/examples/ol3.html). Thanks for help.

**Comment by walkermatt** [comment]
@thomasschmiedl I've not looked at the sidebar before. What have you tried so far?

**Comment by thomasschmiedl** [comment]
I'm not a web-developer. It's only an idea to integrate the layer-switcher in the sidebar.

**Comment by infostar31** [comment]
Hi,
I am trying to display the panel of the ol3 Layerswitcher in a sidebar outside in addition to the the button inside the map, but it doesn't work with me, I don't know where is the problem;
in the JS :
`   map.addControl(new ol.control.LayerSwitcher());
    map.addControl(new ol.control.MousePosition({
                    undefinedHTML: 'Coordonnees', 
                    projection: 'EPSG:4326',
                    coordinateFormat: function(coordinate) {
                        return ol.coordinate.format(coordinate, '{x}, {y}', 5);
                    }
                }));
	map.addControl(new ol.control.OverviewMap({
                    collapsed: false
                }));
    map.addControl(new ol.control.ScaleLine());	

 
	var layerswitcher = new ol.control.LayerSwitcher({
		div: document.getElementById('layerswitcher') }
		);
	map.addControl(layerswitcher);
	layerswitcher.showPanel();`

Can you help me please.

Thank you
