### ISSUE TITLE
add to custom build

### ISSUE THREAD

**Issue by AndyColson** [walkermatt/ol-layerswitcher#47]
Following [the doc on custom builds](http://openlayers.org/en/latest/doc/tutorials/custom-builds.html) works ok, until I try to include the layerswitcher.

In my custom.json file, I added:
```javascript
	"js": [
		"../../ol3-layerswitcher/src/ol3-layerswitcher.js"
	],
```
and in the exports I added "ol.control.LayerSwitcher".

The compile errors:
> ERR! No matching symbol found: ol.control.LayerSwitcher 

I tried to add ol3-layerswitcher.js to the extern as well as the js, neither work, I get the same error.

If I dont add "ol.control.LayerSwitcher" to the exports, then it compiles fine, but my browser errors with:

> TypeError: ol.control.LayerSwitcher is not a constructor

I'd be grateful for any pointers.

**Comment by AndyColson** [comment]
Oh, I almost forgot, setVisible_'s comments needed fixed: 
> * @param {ol.layer.Base} lyr The layer whos visibility will be toggled.
> * @param {Boolean} visible set visibility

~ line 140

**Comment by walkermatt** [comment]
Hi, I've not created a custom build which includes code from outside the core OL3 code base before. Where is the use of a `"js"` key in the build config json documented?

**Comment by AndyColson** [comment]
In the custom build docs, section "Other compiler options", says:
> There is a full list of available options in [closure-util](https://github.com/openlayers/closure-util/blob/master/compiler-options.txt)

I don't really understand the js vs extern difference.  In samples on [this page](http://openlayers.org/en/latest/doc/tutorials/closure.html) they have the olx.js and oli.js in 'js' instead of 'extern', I have no idea why.

**Comment by cdCarlos** [comment]
@AndyColson Did you success integrating ol3-layerswitcher? I'm facing the same issue.

**Comment by AndyColson** [comment]
I did not.  I put the project on hold and haven't gotten back to it.

**Comment by walkermatt** [comment]
@cdCarlos do you have a minimal project which demonstrates the issue that you can share?
