### ISSUE TITLE
Issues in multi map for Prefix option functionality.

### ISSUE THREAD

**Issue by gowthamidhandapani** [walkermatt/ol-layerswitcher#474]
Validated prefix option for state storage functionality in the provided multimap example and below are the list of observations.

**Common Issues for all the mobile and desktop browsers:**

1. If I select the basemap radio button on the top page, the one on the bottom disappears and viceversa.
2. Icon and text display in layer control for data layers are not aligned and correct. Have already raised this as a bug in Jira under the ol-ishare project (v1.1 release). (OLI-288).
3. The layer control doesnt have a scroll bar when more layers are added to the layer switcher and instead the base map options are getting hidden or not visible on the map.Have already raised this as a bug in Jira under the ol-ishare project (v1.1 release). (OLI-289).

**Safari(iOS):**

1. The page has been loaded with a single map not with 2 states of maps.
But I am able to make changes for both the maps through developer tools (edMap and polMap) and i could see changes visibly for edMap and not polMap.

[V1.1 Release_ Multimap_prefix_option_Issues.docx](https://github.com/walkermatt/ol-layerswitcher/files/7001545/V1.1.Release_.Multimap_prefix_option_Issues.docx)

**Comment by walkermatt** [comment]
@gowthamidhandapani thanks for raising this. I'm going to focus on the radio button issue as I believe the others should be addressed in the ol-ishare project.

**Comment by gowthamidhandapani** [comment]
@walkermatt There is another issue in the multimap example on Safari(iOS) browser.
**Safari(iOS):**
The page has been loaded with a single map not with 2 states of maps.
But I am able to make changes for both the maps through developer tools (edMap and polMap) and I could see changes visibly for edMap and not polMap.

**Comment by walkermatt** [comment]
@gowthamidhandapani @devsupportman I'm going to close this issue as the base map radio button issue is resolved.

@gowthamidhandapani I've just looked into an resolved the issue with only a single map displaying on iOS/ Safari which was due to the CSS on the page and not related to the ol-layerswitcher :+1:
