### ISSUE TITLE
Add CSS to scroll when needed by default

### ISSUE THREAD

**Issue by walkermatt** [walkermatt/ol-layerswitcher#475]
Currently when the layer switcher is displaying more layers than will fit vertically those layers at the bottom are hidden from view. The scroll example demonstrates how to set a `max-height` and display a scroll bar when needed but this needs to be manually configured.

This is to propose the following CSS which would limit the height of the layer switcher to just above bottom of the map allows a space for the attribution control:

```css
.layer-switcher.shown {
    max-height: calc(100% - 5.5em);
    overflow-y: auto;
}
```

**Comment by devsupportman** [comment]
This seems like a reasonable default.

**Comment by richard-thomas** [comment]
Definitely agree it would be good to make it scroll by default. However, with activationMode == 'click', the closer button scrolls up and out of sight as the button is part of the layer-switcher div. I have solved this issue in my code by using "fixed" positioning for the button as follows (I have also moved the closer over to the right as a personal preference):

```
.layer-switcher.shown {
    max-height: calc(100% - 5.5em);
    overflow-y: auto;
}
.layer-switcher.shown.layer-switcher-activation-mode-click > button {
    position: fixed;
    right: 0.5em;
    left: auto;
}
```
However, if you exclude the "right: 0.5em;" then this breaks your normal positioning of the closer just to the left of the menu top (it forces it to the far left), so you would need something else as a default.

**Comment by walkermatt** [comment]
Thanks @richard-thomas I'll take a look

**Comment by paul121** [comment]
This would be a welcome change! We did something more rudimentary for our implementation of the layer switcher in farmOS-map: https://github.com/farmOS/farmOS-map/pull/101

One minor issue with this approach is that the bottom border is is not displayed when there are lots of layers. When setting `max-height` to a fixed value it seems to keep the border:

Using `max-height: calc(100% - 5.5em)` | Using `max-height: 300px`
|<img width="262" alt="Screen Shot 2021-09-14 at 5 03 44 PM" src="https://user-images.githubusercontent.com/3116995/133350373-187b2fde-bbb0-4f58-8d0a-ae29e8ee8497.png">|<img width="262" alt="Screen Shot 2021-09-14 at 5 04 09 PM" src="https://user-images.githubusercontent.com/3116995/133350375-8c85d947-3889-4daa-b45f-59cef45e8aba.png">|

**Comment by devsupportman** [comment]
Have you tried something like this?
```css
.layer-switcher.shown {
    overflow-y: hidden;
    display: flex;
    flex-direction: column;
    max-height: calc(100% - 5.5em);
}```
Then the scrolling is done inside the `.panel` element.

**Comment by richard-thomas** [comment]
> Have you tried something like this?
> 
> ```css
> .layer-switcher.shown {
>     overflow-y: hidden;
>     display: flex;
>     flex-direction: column;
>     max-height: calc(100% - 5.5em);
> }```
> Then the scrolling is done inside the `.panel` element.
> ```

Flexbox might be an issue in Internet Explorer 11; I've not tried (my app doesn't support IE11, but others might want), but looking at notes when height isn't explicitly defined in:

https://caniuse.com/flexbox

**Comment by walkermatt** [comment]
Given that [IE11 is soon out of support](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge#is-internet-explorer-11-the-last-version-of-internet-explorer-) and may people have already dropped support I'm in favour of adopting the flexbox approach; should IE11 support be required then it can be supported by adding a fixed `max-height` just for IE11 like so:

```css
/* Fixed max-height for IE11 to support scrolling, due to incomplete support for flexbox */
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {

  .layer-switcher.shown {
    max-height: 170px;
  }

}
```

**Comment by walkermatt** [comment]
[Example of the above approach which should scroll reliably on modern browsers and IE11](https://raw.githack.com/walkermatt/ol-layerswitcher/scroll/examples/scroll.html).

Changes: https://github.com/walkermatt/ol-layerswitcher/commit/2115f8e591fdd2add93bcc92d9e301a7d430a096.
