### ISSUE TITLE
Selection of layers that depend on other layers

### ISSUE THREAD

**Issue by alexgao1** [walkermatt/ol-layerswitcher#482]
Using https://raw.githack.com/walkermatt/ol-layerswitcher/master/examples/select-groups.html as example, given the structure of:  

> Census  
>   - Wards
>   - Districts

Could it be possible to make it such that it becomes something like:

> Wards
>   - Districts

so that checking off wards will show wards, and that districts can be toggled on or off regardless of wards, but toggling wards off will also disable districts?

If that isn't possible, then can there be an option to hide just one layer such that a similar effect can be recreated: 

> Wards  
>   - Wards (_but hidden from the panel_)
>   - Districts

**Comment by alexgao1** [comment]
Would it also be possible to set whether or not layers are checked off or not upon creation of the layer switcher? (Not wanting all layers on by default)

**Comment by walkermatt** [comment]
Hi,

The initial visible state of the layers can be set for individual layers either by [specifying a `visible` option](https://github.com/walkermatt/ol-layerswitcher/blob/master/examples/layerswitcher.js#L88) or by calling `setVisible` on a layer instance.

**Comment by alexgao1** [comment]
Okay, that works for initially setting a layer to be not visible.  
  
Is there a solution for the first issue that I described about a layer's visibility being dependent on another layer?

**Comment by walkermatt** [comment]
I don't think you need anything LayerSwitcher specific to solve your first requirement. You can hide the dependent layer from the LayerSwitcher by not giving it a `title` property and toggle it's visibility within a `change:visible` [listener on the other layer](https://openlayers.org/en/latest/apidoc/module-ol_layer_Base-BaseLayer.html#on).

**Comment by alexgao1** [comment]
That worked out, makes sense.  

Thank you.
