### ISSUE TITLE
Make it possible that layer names can be hyperlinks

### ISSUE THREAD

**Issue by skitourenguru** [walkermatt/ol-layerswitcher#485]
With the **title** properties we can name a layer. However it would be useful to transform the name into a hyperlink. Therefor a new property **url** could be defined side by side to the **title** property.

**Comment by DL-Works** [comment]
Can you describe the purpose of doing it?

**Comment by skitourenguru** [comment]
If the user clicks on the link he can find information about the layer.

The issue is 2 years old. By the time I implemented my own layer switcher. If its for me you can close the issue.

**Comment by walkermatt** [comment]
@skitourenguru thanks for confirming, your layer switcher looks great.
