### ISSUE TITLE
PluggableMap class removed from OL7

### ISSUE THREAD

**Issue by adhaca** [walkermatt/ol-layerswitcher#489]
The PluggableMap class has been removed in [Openlayers 7](https://github.com/openlayers/openlayers/releases/tag/v7.0.0). But ol-layerswitcher v4.0.0 is still trying to import it. Is it possible to replace it with the regular Map class?

**Comment by walkermatt** [comment]
Good catch, I guess that makes the types incompatible with ol v7.

Would you be happy submitting a pull request?
