### ISSUE TITLE
Use with requirejs

### ISSUE THREAD

**Issue by akshayvasishth** [walkermatt/ol-layerswitcher#49]
@walkermatt Could you please provide an example on how to load this library using requirejs.
I get undefined object when i try to do so:-
require(["./ol3-layerswitcher"],function(layerSwitcher){ }

**Comment by walkermatt** [comment]
I'm not sure, I'd like to figure it out myself :smile_cat: so that I can verify the changes in @francbartoli's pull request #48

Do you have a basic project that you could share (as a gist or similar) which I could take a look at?

**Comment by walkermatt** [comment]
Closed due to inactivity.
