### ISSUE TITLE
Remove polyfill.io from the examples (Security, Privacy)

### ISSUE THREAD

**Issue by AxxL** [walkermatt/ol-layerswitcher#503]
The examples contain links to polyfill.io to get around incompatibilities with other browsers.

Recently, a supply chain attack was built into polyfill. It is not recommended to use the library anymore!

See: https://sansec.io/research/polyfill-supply-chain-attack
See also issue in polyfill (might be removed by maintainer): https://github.com/polyfillpolyfill/polyfill-service/issues/2890

Code example:
`<script src="https://cdn.polyfill.io/v2/polyfill.min.js ...`

Any link to cdn.polyfill.io should be removed, the library should not be used.

**Comment by walkermatt** [comment]
@AxxL thanks for reporting, should now be resolved.
