### ISSUE TITLE
hovering over the layer switcher icon it dissappears

### ISSUE THREAD

**Issue by ls91** [walkermatt/ol-layerswitcher#506]
When I hover over the layer switch icon it collapses to the right and I'm unable to click on it to open the layer switcher up.

I am using:
- OpenLayers: 10.1.0
- LayerSwitcher: 4.1.2

Issue was replicated in:
- Microsoft Edge: Version 128.0.2739.79
- Chrome: Version 121.0.6167.86

**Comment by ls91** [comment]
I missed the line about supported OpenLayer versions, but i back versioned to ol@6.15.1 and this is still an issue.

**Comment by walkermatt** [comment]
Hi, if you can share a https://codesandbox.io/ sandbox (or similar) which reproduces the issue I'll happily take a look.

**Comment by ls91** [comment]
https://codesandbox.io/p/devbox/modest-forest-z3q5z3?workspaceId=aff9888e-7567-4a7a-b0eb-e3ba1a15405a

**Comment by walkermatt** [comment]
@ls91 I think you're missing the `title` properties on your layers.

I've added a `title` and `type: 'base'` to the OSM layer and a title to the other layer which causes the layers to be displayed in the layer switcher:

![image](https://github.com/user-attachments/assets/011fea0f-c825-4b78-96d8-f1d67fdf3787)

**Comment by ls91** [comment]
Thanks @walkermatt , you're right, adding the titles it opens and closes as expected.
