### ISSUE TITLE
Layer opacity slider

### ISSUE THREAD

**Issue by sookoll** [walkermatt/ol-layerswitcher#58]
I created a fork with layer opacity sliders:
https://github.com/sookoll/ol3-layerswitcher

Demo: https://jsfiddle.net/u5ucn87f/

If there is need for that, I can create a pull request.

**Comment by walkermatt** [comment]
Hi, Just had a look at [the opacity slider example](http://rawgit.com/sookoll/ol3-layerswitcher/master/examples/opacity_slider.html) and I like it. My initial thought is that it might be nice if it was a per layer option.

@ThomasG77 , @tomchadwin thoughts?

**Comment by tomchadwin** [comment]
A big +1 from me. It's been requested, and its use is obvious. Plus, Leaflet can't currently do it (though it's fixed in master):

https://github.com/Leaflet/Leaflet/issues/5116

**Comment by walkermatt** [comment]
@tomchadwin any preference as to whether it should be enabled globally for all layers or enabled for individual layers?

**Comment by tomchadwin** [comment]
Per-layer, I'm afraid. It makes most sense for rasters/basemaps and filled polys, less so for points/lines, so having it on-demand rather than throughout is probably what's needed. What do you think?

**Comment by Saurbaum** [comment]
To chip in on the matter.

Per layer but also some way to turn it on or off in code so I can limit it to not being available for a the base layers should I want.

@sookoll Does it pick up a configured opacity on the layer if it's already at 50% and set the slider accordingly?

**Comment by sookoll** [comment]
Yes, same manner as layer visibility. In that sence, per layer configuration would be natural choise. Current solution (global setting) was just first obvious solution for my need.

**Comment by tomchadwin** [comment]
To clarify my point, yes, per-layer, but also, as @Saurbaum says, the default should be for the slider not to show for a layer, but it could be enabled as an option.

**Comment by sookoll** [comment]
A quick fiddle for demonstration: https://jsfiddle.net/u5ucn87f/
I think I can push it further and implement also per-layer configuration. Per-layer configuration as layer property in third party library is a bit dangerous way. What if ol Feature API changes and take same property into use, or user already use this property for some purpouse, etc. So any suggestion about property name would be welcome.

`opacitySlider: true` ?

Also better suggestions for control's option name (current is enableOpacitySliders)

**Comment by tomchadwin** [comment]
@sookoll Are you warning about creating a new property for the `layer` object in core OL? I was thinking rather that there should be some way of passing per-layer config into the layerswitcher.

**Comment by sookoll** [comment]
I meant currently it already depends custom layer properties like "title". If no title, then no layer in layerswitcher, right. To keep same logic, I assume that we take another property into use. It would be straightforward but it might conflict to some other libraries (as also "title" currently). Passing in configuration as reference to layers is not so straightforward and more difficult to implement, so it is question of decision here.

**Comment by tomchadwin** [comment]
OK, so two possible quite "safe" options:

1. Namespace our layer options = `layerSwitcher_title`, `layerSwitcher_opacityslider` etc

2. As I suggested (but it s fundamental change to layerswitcher), pass layer config in when you instantiate the layer switcher:

```javascript
var layerSwitcher = new ol.control.LayerSwitcher({
    tipLabel: 'Légende' // Optional label for button,
    layers: [
        {layer: layer1,
        opacitySlider: true},
        {layer: layer2,
        opacitySlider: false}]
});
map.addControl(layerSwitcher);
```

This would allow removing the requirement for the `title` property in layers, as it could be added as a property passed when instantiating the switcher. This could also then allow embedded HTML (ie layer key icons) in the switcher.

**Comment by SFPink** [comment]
Great fork, this is exactly what I was looking for.

What was the final conclusion on the per layer opacity toggle?

**Comment by SFPink** [comment]
I have hashed together working example of @tomchadwin idea so the Layer Switcher can work as he suggested, I can fork this project if anyone is interested:

`var layerSwitcher = new ol.control.LayerSwitcher({
    tipLabel: 'Légende' // Optional label for button,
    layers: [
        {layer: layer1,
         title: '<img src="path/to/layer1KeyIcon.png" alt="Layer 1 title" /> Layer 1 title',
         opacitySlider: true},
        {layer: layer2,
         title: '<img src="path/to/layer1KeyIcon.png" alt="Layer 1 title" /> Layer 1 title',
         opacitySlider: false}]
});`

**Comment by tomchadwin** [comment]
Sounds great to me, but I don't know if it's too big a change for @walkermatt to consider. If you are prepared to fork so we can see it in action, we could judge. And thanks!

**Comment by SFPink** [comment]
Personally I think the change is too much. But I will happily create a fork.

**Comment by tomchadwin** [comment]
Interesting. You don't think the benefits justify it?

- stop adding own properties to OL core object (so avoid risk of naming conflict in the future, as @sookoll said)
- better decoupling of the layer switcher from the layers
- enables this issue's aim (per-layer opacity sliders)
- great flexibility to add future properties if required

**Comment by SFPink** [comment]
I think it's a great addition don't get me wrong and your points are very valid. My only issue personally is that there is no legacy support, not that it affects me. 

Here's my fork: https://github.com/SFPink/ol3-layerswitcher

I put this together this morning whilst half asleep, let me know if you discover any issues. I currently have this working in one of my projects.

I've also added an onOpacityChange and onLayerToggle, these aren't per control but could be.

**Comment by eflowbeach** [comment]
@walkermatt Do you plan to add this functionality to the ol3-layerswitcher? I noticed this was discussed a few years ago.

**Comment by MaxDragonheart** [comment]
News about the adding of this functionality

**Comment by walkermatt** [comment]
Hi, adding an opacity slider isn't currently under consideration.

**Comment by ThomasG77** [comment]
I'm not sure it's better to try increasing the scope of ol-layerswitcher when other OpenLayers layer switcher projects are intended for complex cases.
So, for complex layer switcher, you may look at ol-ext project sample e.g https://viglino.github.io/ol-ext/examples/control/map.switcher.html or a my simplified forked version e.g https://gist.githack.com/ThomasG77/8cb1fddc64d4b3d8c6e7d76ad1d20dd4/raw/3d80fb33c12712bcb53acbd89ab98761907db758/index.html
ol-ext can work with standalone Openlayers or using bundle manager like webpack

**Comment by walkermatt** [comment]
Thanks @ThomasG77, as it happens @devsupportman is currently looking at the feasibility of allowing a function to be supplied that would allow the markup for a layer to be customised. In theory this might allow adding additional controls such as an opacity slider.
