### ISSUE TITLE
repo npm sync?

### ISSUE THREAD

**Issue by WillieMaddox** [walkermatt/ol-layerswitcher#59]
After running, `npm install ol3-layerswitcher`, the `node_modules/ol3-layerswitcher/package.json` reads (only the relevant parts are printed here for brevity),

```js
{
  "dependencies": {
    "openlayers": "~3.17.1"
  },
  "keywords": [
    "openlayers",
    "layerswitcher",
    "ol3"
  ],
  "version": "1.1.2"
}
```

Looks like the version is up-do-date, but the dependencies aren't in sync with the most recent commits (openlayers still points to `3.x.x` and the keyword still says `ol3` rather than just plain `ol`. There are other places with discrepancies, I just listed a few here for example.  Is there a way to fix/sync this?

-W

**Comment by walkermatt** [comment]
@Renaud009 I've just tagged the latest version of ol3-layerswticher, could you please update https://www.npmjs.com/package/ol3-layerswitcher. I'd be happy to take ownership of the package on npm and maintain it from now on.

**Comment by walkermatt** [comment]
@Renaud009 would you be able to update https://www.npmjs.com/package/ol3-layerswitcher with the latest version?

**Comment by ahocevar** [comment]
Maybe it's time for a new major release that supports the `ol` package instead of `openlayers`? That could be published as https://npmjs.com/package/ol-layerswitcher/, which is currently maintained by @francbartoli.

The current ol3-layerswitcher package can be used with the `ol` package, but it is a nightmare because it installs `openlayers` and all its headache dependencies. It also requires insane shimming in the webpack config:
```js
  module: {
    rules: [
      {
        test: require.resolve('ol3-layerswitcher/src/ol3-layerswitcher.js'),
        loader: 'imports-loader?olPkg=ol,Control=ol/control/Control,root=>{ol:{control:{}}};root.ol.control.Control=Control.default;root.ol.inherits=olPkg.default.inherits,this=>root,define=>{},module=>{}'
      },
      {
        test: require.resolve('ol3-layerswitcher/src/ol3-layerswitcher.js'),
        loader: 'exports-loader?LayerSwitcher=root.ol.control.LayerSwitcher'
      }
    ]
  },
```

**Comment by walkermatt** [comment]
@ahocevar I agree, I think a new major version is in order. I'll give it some though over the holidays.

**Comment by walkermatt** [comment]
The latest version can be found on npm at https://www.npmjs.com/package/ol-layerswitcher.

Note that v2.0.0 supports the [`ol` package](https://www.npmjs.com/package/ol) and the hosted build but not the "old" [`openlayers` package](https://www.npmjs.com/package/openlayers).
