### ISSUE TITLE
Nested groups

### ISSUE THREAD

**Issue by tomchadwin** [walkermatt/ol-layerswitcher#62]
Are nested groups supported? Apologies if I've asked this before, but I couldn't see it in the issues.

**Comment by walkermatt** [comment]
The good news is that currently nested groups are supported:

![nested](https://user-images.githubusercontent.com/600349/29686631-a4a86bbe-8911-11e7-99ad-fff926132053.png)

The bad news is that #60 doesn't currently work well with nested groups.

**Comment by jubmailto** [comment]
Apologies for this question but can you show me the lines of code for nested groups please ? Thank you

**Comment by walkermatt** [comment]
The ability to nest and expand/ contract a group has been available for a little while. See the comments regarding `fold` in [../examples/layerswitcher.js](../examples/layerswitcher.js).
