### ISSUE TITLE
Enable and disable parent layers as well as child layers

### ISSUE THREAD

**Issue by seema30fresher** [walkermatt/ol-layerswitcher#63]
I have used ol3-layerswitcher,I wan't to enable parent layer checkbox at that time all child layers checkbox get enable and vise versa.If some child layers are disabled and i enable parent layer then all child layers should be enable.I tried little bit code with html check boxes and JS  but my code not working properly and code is too big .Please find this [http://uxo.azurewebsites.net/webmap/Index.html] Thanks

**Comment by seema30fresher** [comment]
Please help me anyone to solve this problem.

**Comment by SFPink** [comment]
Is this what you are after: https://github.com/walkermatt/ol3-layerswitcher/pull/60

**Comment by seema30fresher** [comment]
Not exactly but on similar line, Whenever we enable parent all child will enable and vice versa as well as when i disable any one child and enable parent then all child has to be enable. like suppose i have parent with 10 child whenever i have disabled couple of child (lets consider 4) parent layers will show disabled as its not fulfilling condition of all child enabled now i directly enable parent then all 10 child has to be enabled but right now its not working in such a way only previously enabled child are shows in after parent enabling.  please refer this webmap similar [link]( http://gis.mail.gov.af/afdv) logic of layer switcher i am looking for.

**Comment by walkermatt** [comment]
I've just published [v3.3.0](https://www.npmjs.com/package/ol-layerswitcher/v/3.3.0) which I think covers this use case, see the [`groupSelectStyle` option in the docs](../#layerswitcher) and Selectable groups example (under [examples](../#examples)).
