### ISSUE TITLE
option to control layer reverse

### ISSUE THREAD

**Issue by Hanmac** [walkermatt/ol-layerswitcher#72]
i only found out recently that the layer of this widget are reversed.

it would be nice, if it would been nice if he widget could have an option to disable the layer reverse

i might do a PR for this if wanted

**Comment by ThomasG77** [comment]
See https://github.com/walkermatt/ol3-layerswitcher/pull/2 for the origin (PS: I'm responsible for this particular change in the code base)
After, it's up to @walkermatt to make a decision to restore or not the possibility to make the choice to "reverse" layers in the plugin.

**Comment by walkermatt** [comment]
I think this has came up a couple of times now. I'd be happy to consider a PR that adds an option. I think I like the idea of a `reverse` option which defaults to `true`.
