### ISSUE TITLE
Seed with layers from WMS GetCapabilities request

### ISSUE THREAD

**Issue by geraldo** [walkermatt/ol-layerswitcher#73]
Did you think of extending your great plugin by adding the possibility of automatically create layers and layer groups from a WMS GetCapabilities request?

I imagine  something like:
1. A parameter to indicate the GetCapabilities URL
2. Fetching WMS XML
3. Parsing the XML by using [ol.format.WMSCapabilities()](https://openlayers.org/en/latest/apidoc/ol.format.WMSCapabilities.html)
4. Building the layers array setting up ol.layer.Group and ol.layer.Tile objects

Is this something you could imagine to integrate in your plugin if I work on it or should this be done better in a separate plugin?

**Comment by walkermatt** [comment]
I like the idea but I think it would make sense for the functionality you outline to be in it's own plugin. That way users can benefit from this functionality without the need for the ol-layerswitcher.

If the plugin follows the same conventions as the ol-layerswticher then we get the best of both worlds and I'd be happy to include an example/ link.

One thought on functionality is that it would be great if there was the option to create individual layers or all layers within a group from a GetCapabilties response as well as creating the entire tree.

Happy to help with testing 😸

**Comment by ThomasG77** [comment]
Too incomplete at the moment but you can look at https://github.com/ThomasG77/wms-selector for some clues.

**Comment by geraldo** [comment]
Thanks for the hints, but I have to spare them for later. For the actual project I had to use a different approach as GetCapabilities doesn't show all properties I need to pass to my web map. Actually I had to get the info directly out of my QGIS project file...
