### ISSUE TITLE
Angular 5 - Typescript example

### ISSUE THREAD

**Issue by XeZZoR** [walkermatt/ol-layerswitcher#75]
I am trying to get one of the example to work with Angular and Typescript. 
But I always get ERROR TypeError: ol_layerswitcher_1.default is not a constructor.

Can you adapt one of your examples for Typescript maybe?

**Comment by digoburigo** [comment]
Hey, i'm trying this too, I change the "target" to es6 in the tsconfig.json file and this error is gone. The layerswitcher shows up but dont work properly, so i think this maybe must be adapted for Angular and Typescript

**Comment by digoburigo** [comment]
`const optionsOSM = {
      title: 'Open Street Map',
      type: 'base',
      visible: true,
      source: new OSM()
    };
this.osm = new LayerTile(optionsOSM);`

**Comment by digoburigo** [comment]
``
const tileOptions = {
      url: 'http://34.215.151.102:8181/geoserver/wms',
      params: { 'LAYERS': 'criciuma:lotes', 'SRS': 'EPSG:4326', 'WIDTH': '256', 'HEIGHT': '256', 'FORMAT': 'image/jpeg', 'TILED': true, 'BBOX': true },
      serverType: 'geoserver',
      // Countries have transparency, so do not fade tiles:
      transition: 0
    };
    const sourceTile = new TileWMS(tileOptions);
    const tileWMSoptions = {
      title: 'Lotes',
      source: sourceTile,
      visible: false
    };
    const tileWMS = new LayerTile(tileWMSoptions);
``

**Comment by digoburigo** [comment]
```
const tileOptions = {
      url: 'http://34.215.151.102:8181/geoserver/wms',
      params: { 'LAYERS': 'criciuma:lotes', 'SRS': 'EPSG:4326', 'WIDTH': '256', 'HEIGHT': '256', 'FORMAT': 'image/jpeg', 'TILED': true, 'BBOX': true },
      serverType: 'geoserver',
      // Countries have transparency, so do not fade tiles:
      transition: 0
    };
    const sourceTile = new TileWMS(tileOptions);
    const tileWMSoptions = {
      title: 'Lotes',
      source: sourceTile,
      visible: false
    };
    const tileWMS = new LayerTile(tileWMSoptions);
 ```

**Comment by digoburigo** [comment]
Hey man, i have found a solution. In my code i made a object for every parameters for my layers and layerGroups.
Below is how my code works.
```
const optionsOSM = {
      title: 'Open Street Map',
      type: 'base',
      visible: true,
      source: new OSM()
 };
this.osm = new LayerTile(optionsOSM);

const tileOptions = {
      url: 'example',
      params: { example... },
      serverType: 'example',
      // Countries have transparency, so do not fade tiles:
      transition: 0
 };
const sourceTile = new TileWMS(tileOptions);
const tileWMSoptions = {
      title: 'example',
      source: sourceTile,
      visible: false
};
const tileWMS = new LayerTile(tileWMSoptions);

// --- Layers Groups
const layerGroupOptions = {
      title: 'Maps',
      layers: [this.osm]
};
const layerGroupMap = new LayerGroup(layerGroupOptions);
const overlayGroupOptions = {
      title: 'Overlay',
      layers: [tileWMS]
};
const overlayGroup = new LayerGroup(overlayGroupOptions);
// ---
this.map = new OlMap({
      target: this.mapElement.nativeElement,
      layers: [
        // layersGroups ...
        layerGroupMap,
        overlayGroup
      ],
      view:  your view ...
});
 ```
If you have any doubts, just ask. Sorry for my bad english :)

**Comment by oehm-smith** [comment]
Given this is closed I will open a new ticket for my concerns. It is #272.
