### ISSUE TITLE
Integration with permalink

### ISSUE THREAD

**Issue by woodbri** [walkermatt/ol-layerswitcher#77]
It would be nice if you had an example of how to integrate with permalink. While this might be obvious to other programmers it is not to users that can do some elite hacking of the code. :)

**Comment by walkermatt** [comment]
Hi, which permalink implementation are you using? The layer switcher is dependant on the layers within the map and is rendered each time the panel is shown so I don't think there's likely to be any direct interaction required between permalink functionality and the layer switcher.

**Comment by woodbri** [comment]
I'm use the one from the openlayers examples which is not a control:
https://openlayers.org/en/latest/examples/permalink.html#map=2/0/0/0

    map=<zoom>/<x>/<y>/<rotation>

I think in OL2 they would do something like adding /0,1,0,0,1,1 to the url like:

    map=<zoom>/<x>/<y>/<rotation>/<layer_visibility_list>

where these were boolean on/off for the array of layers then when the page was loaded the handler would set the visibility for those layers. When the layer switcher notices a change in layer visibility it would update the url as appropriate. I'm not sure how/if layer groups or base vs overlay layers would impact this.

**Comment by walkermatt** [comment]
I think this functionality is probably better implemented independently of ol-layerswitcher. It might be worth asking over at  https://github.com/tschaub/ol-hashed.
