### ISSUE TITLE
Module names-related errors while using with Angular6-OL5

### ISSUE THREAD

**Issue by spimou** [walkermatt/ol-layerswitcher#79]
I am using Angular 6 and OpenLayers 5.1.3. I installed the ol-layerswitcher by doing `npm i ol-layerswitcher --save` and it is installed in the `node_modules` of the node folder

```
project
-angular
-lib
-node_modules <<Here
-routes
-app.s
-package.json
```

To insert it in my angular code, in my angular component I do  
```
import layerswitch from 'ol-layerswitcher';
export class myComponent {
  ngOnInit() {    
    this.olmap = new Map({
      controls: defaultControls({
        attributionOptions: {
          collapsible: false
        }
      }).extend([
        new ZoomToExtent({
          extent: [
            813079.7791264898, 5929220.284081122,
            848966.9639063801, 5936863.986909639
          ]
        }),
        new layerswitch({})//use it here
      ]), 
      layers: [this.tilelayer,this.vectorlayer],
      target: 'map',      
      view: this.view,
      projection: 'EPSG:3857'
    });
  }
}
```

This works fine, the map in the UI and the ol-layerswitcher work, but I get the following errors in my console

```
WARNING in ../node_modules/ol/Observable.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\myproject\node_modules\ol\Observable.js
    Used by 4 module(s), i. e.
    C:\myproject\node_modules\ol\Object.js
* C:\myproject\node_modules\ol\observable.js
    Used by 1 module(s), i. e.
    C:\myproject\node_modules\ol-layerswitcher\dist\ol-layerswitcher.js

WARNING in ../node_modules/ol/control/Control.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\myproject\node_modules\ol\control\Control.js
    Used by 18 module(s), i. e.
    C:\myproject\node_modules\ol\control.js
* C:\myproject\node_modules\ol\control\control.js
    Used by 1 module(s), i. e.
    C:\myproject\node_modules\ol-layerswitcher\dist\ol-layerswitcher.js
i ｢wdm｣: Compiled with warnings.
```
I am an angular newbie and I have not used OL in years, so I am confused, please help to understand what those errors mean and how to fix them. 

Thank you very much

**Comment by walkermatt** [comment]
I think this is due to us needing to update the layerswitcher to OpenLayers v5. I've just created [an `ol5` branch](https://github.com/walkermatt/ol-layerswitcher/tree/ol5) for the work.

If you update your `package.json` to specify `git+https://github.com/walkermatt/ol-layerswitcher.git#ol5` as the "version" you should be able to test against an OpenLayers v5 compatible version of the layerswitcher.

**Comment by walkermatt** [comment]
It's probably worth deleting your node_modules directory, running `npm install` again then rebuilding your project.

**Comment by spimou** [comment]
So, delete everything that is inside node server's `node_modules` folder, run `npm install` to get the modules re-installed. How this will help, what are we trying to achieve here? I guess its way too risky now, since my project is already pretty big and I am afraid that something may break.  What other options do I have here? Maybe the way I am importing the `ol-layerswitcher` or other parts of OL? I was getting the same errors when wrongly importing OL, that where fixed when I changed the syntax.

Thanks again

**Comment by walkermatt** [comment]
In that case try just removing the ol-layerswitcher package:

```
npm uninstall ol-layerswitcher --save
```
Then installing specifying the git repo/ branch:

```
npm install git+https://github.com/walkermatt/ol-layerswitcher.git#ol5 --save
```

**Comment by spimou** [comment]
Oh yeah, works perfectly, no errors or warnings. Thanks for your time and effort Matt. Keep up the good work. For additional info about the structure or the code, feel free to ask.

**Comment by stackedone** [comment]
I got the same warnings with 
`"ol": "^5.3.0",
    "ol-layerswitcher": "^3.2.0",`

`WARNING in ./node_modules/ol/Layer/Base.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/wim/development/ng7-demo/node_modules/ol/Layer/Base.js
    Used by 2 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/Layer/Layer.js
* /Users/wim/development/ng7-demo/node_modules/ol/layer/Base.js
    Used by 4 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/layer/Group.js

WARNING in ./node_modules/ol/Layer/Layer.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/wim/development/ng7-demo/node_modules/ol/Layer/Layer.js
    Used by 2 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/Layer/Tile.js
* /Users/wim/development/ng7-demo/node_modules/ol/layer/Layer.js
    Used by 9 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/layer/Vector.js

WARNING in ./node_modules/ol/Layer/Property.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/wim/development/ng7-demo/node_modules/ol/Layer/Property.js
    Used by 22 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/Layer/Layer.js
* /Users/wim/development/ng7-demo/node_modules/ol/layer/Property.js
    Used by 22 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/layer/Base.js

WARNING in ./node_modules/ol/Source/Source.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/wim/development/ng7-demo/node_modules/ol/Source/Source.js
    Used by 2 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/Source/Tile.js
* /Users/wim/development/ng7-demo/node_modules/ol/source/Source.js
    Used by 2 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/source/Vector.js

WARNING in ./node_modules/ol/Source/State.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/wim/development/ng7-demo/node_modules/ol/Source/State.js
    Used by 2 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/Source/Source.js
* /Users/wim/development/ng7-demo/node_modules/ol/source/State.js
    Used by 14 module(s), i. e.
    /Users/wim/development/ng7-demo/node_modules/ol/layer/Group.js
`
