### ISSUE TITLE
Remove Layer from Group

### ISSUE THREAD

**Issue by thomasschmiedl** [walkermatt/ol-layerswitcher#98]
Hello,
is it possible, when adding a layer to an existing group after the layer switcher has been added to the map via "overlayGroup.getLayers().push(...);", also remove this layer from the group?
Thanks,
Thomas

**Comment by walkermatt** [comment]
Yes that's possible and core OpenLayers functionality, independent to the layer switcher. The next time you open the layer switcher the current layer state will be displayed.

If for some reason you need to force the layer switcher to refresh after making changes to the layers you can call [`renderPanel`](https://github.com/walkermatt/ol-layerswitcher/#renderpanel) on your layer switcher instance.
