### ISSUE TITLE
Click vs hover to activate

### ISSUE THREAD

**Issue by StuffOfInterest** [walkermatt/ol-layerswitcher#99]
I'm generally happy with the layer switcher but it would be nice to have an option to control activation of the switcher.  Currently, the attribution control requires clicking to activate it and it stays shown until clicked again.  The layer switcher activates on hover and then goes away as soon as you move outside of the switcher.  Having an option to switch the activation mode between "click" and "hover" would be very helpful in presenting a consistent UI experience.

![image](https://user-images.githubusercontent.com/8578647/46297214-299a8d80-c56a-11e8-8808-ba5913321d48.png)

![image](https://user-images.githubusercontent.com/8578647/46297244-41721180-c56a-11e8-9808-087221cb1f19.png)

Also, consider using the same mechanism for presenting the embedded control icon as other controls.  In setting up a sample map, I had zoom, overview, attribution, and layer switcher all enabled (in separate corners of the map).  Using the openlayers icon for the switcher really looks out out place.

**Comment by walkermatt** [comment]
This has come up a couple of times now (this issue and #39).

**Comment by Zvax** [comment]
Not sure if that is related, but if it were possible while thinking about this issue, if it were possible to have an "always open" mode, that would be great as well!

The on mouseover behaviour is excellent when embedded on the map, but when displaying the layer switcher out of it, it could be great to have it always opened.

I'm open to help, if desirable and/or possible, I'm thinking that adding an option in the constructor's options that would trigger or not the rendering of the button, and show or not the panel, could do the trick.

Cheers!

**Comment by walkermatt** [comment]
@Zvax If you're rendering the panel outside the map you can have an "always open" mode now, see https://github.com/walkermatt/ol-layerswitcher/pull/76 and the [Side bar example](https://rawgit.com/walkermatt/ol-layerswitcher/master/examples/sidebar.html).

**Comment by adrelino** [comment]
@StuffOfInterest have a look at #258 (demo: https://raw.githack.com/adrelino/ol-layerswitcher/activation-mode-option/examples/activation-mode-click.html) to see if this suits your needs. The icon can now also be changed if wanted via the option `label`. 
I finally want to get this merged ;-) to avoid any further duplicate efforts.
